# Uncomment this line if you're using Swift
use_frameworks!

target 'HFCardCollectionViewLayoutExample' do
    platform :ios, '10.0'
    pod 'HFCardCollectionViewLayout', :git => 'https://github.com/spclab-ux/HFCardCollectionViewLayout.git', :branch => 'semiRef'
end
